"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# La llave sale del .env, que NO va a GitHub.
#
# Antes estaba escrita aquí, y este archivo sí está en el repositorio: cualquiera
# que viera el repo tenía la llave con la que Django firma las sesiones y los
# tokens de recuperación de contraseña. La que estaba publicada quedó quemada y
# NO se debe volver a usar; en el .env va una nueva, generada aparte.
#
# Para generar una nueva:
#   python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError(
        "Falta DJANGO_SECRET_KEY en backend/.env. Genera una con:\n"
        "  python -c \"from django.core.management.utils import "
        "get_random_secret_key; print(get_random_secret_key())\""
    )

# DEBUG muestra el código fuente y las variables de entorno —incluidas las
# contraseñas de SAP— en cualquier página de error. En producción va apagado.
DEBUG = os.getenv("DJANGO_DEBUG", "True").strip().lower() in ("1", "true", "si", "sí")

# Con DEBUG apagado Django exige saber desde qué dominios se le puede hablar.
# Se listan separados por coma en el .env (ej. "logistica.laben.mx,10.16.0.44").
ALLOWED_HOSTS = [
    h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
] or (["*"] if DEBUG else [])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'delivery',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_NAME = os.getenv('DB_NAME', 'laben_routing')
DB_USER = os.getenv('DB_USER', 'postgres')
DB_PASSWORD = os.getenv('DB_PASSWORD', 'postgres')
DB_HOST = os.getenv('DB_HOST', 'localhost')
DB_PORT = os.getenv('DB_PORT', '5432')

# PostgreSQL es la ÚNICA base de datos en operación. Antes había un fallback
# silencioso a SQLite si Postgres no respondía; se quitó porque generaba una
# segunda fuente de verdad con datos viejos (pedidos/rutas fantasma en el panel)
# sin que nadie se diera cuenta.
#
# La comprobación de que Postgres responde vive en delivery/apps.py:ready(), NO
# aquí. Estaba a nivel de módulo en este archivo, y eso significa que se abría
# una conexión con solo IMPORTAR settings: rompía `collectstatic`,
# `makemigrations --check`, los tests y cualquier CI, y abría una conexión de
# más por cada worker de gunicorn al arrancar.
#
# EXCEPCIÓN para pruebas: con DJANGO_TEST_DB=sqlite se corre contra SQLite en
# memoria. Es lo contrario del fallback que se quitó — aquel era automático y
# silencioso (podías estar trabajando contra datos viejos sin saberlo); éste hay
# que pedirlo a mano por variable de entorno y solo lo usa la suite de pruebas.
if os.getenv('DJANGO_TEST_DB') == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        }
    }

# De dónde se acepta que hable el navegador.
#
# Antes esto era `CORS_ALLOW_ALL_ORIGINS = True` fijo, con un comentario que
# decía "solo para desarrollo" — pero no había nada que lo apagara al salir de
# desarrollo. Con la API sin autenticación, eso significa que cualquier página
# web que el despachador abriera podía leer la cartera de clientes y rehacer el
# plan del día desde su navegador.
#
# Ahora: en desarrollo se permite todo (cómodo, y ahí no hay nada real); en
# producción solo lo que se liste en CORS_ORIGINS del .env.
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.getenv("CORS_ORIGINS", "").split(",") if o.strip()
]
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Monterrey'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Archivos que suben los usuarios: hoy solo las fotos de evidencia que toma el
# chofer al entregar. En producción esto debe apuntar a un disco con respaldo,
# no a la carpeta del proyecto.
# Con diagonal inicial. Sin ella, `remision.foto.url` devuelve una ruta
# RELATIVA ("media/entregas/…"), que el navegador resuelve contra la página
# actual del panel y da 404: las fotos de evidencia no se veían desde ningún
# lado que no fuera la raíz.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
