# Generated by Django 6.0.6 on 2026-07-05 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('camion', models.CharField(max_length=100)),
                ('chofer', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Borrador', 'En preparación'), ('En_Ruta', 'En ruta'), ('Finalizada', 'Finalizada')], default='Borrador', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=50)),
                ('ship_to_code', models.CharField(max_length=100)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('block', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('ini_recibo_1', models.TimeField(blank=True, null=True)),
                ('fin_recibo_1', models.TimeField(blank=True, null=True)),
                ('ini_recibo_2', models.TimeField(blank=True, null=True)),
                ('fin_recibo_2', models.TimeField(blank=True, null=True)),
                ('ent_lun', models.BooleanField(default=True)),
                ('ent_mar', models.BooleanField(default=True)),
                ('ent_mie', models.BooleanField(default=True)),
                ('ent_jue', models.BooleanField(default=True)),
                ('ent_vie', models.BooleanField(default=True)),
                ('ent_sab', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('card_code', 'ship_to_code')},
            },
        ),
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_entry', models.IntegerField(unique=True)),
                ('doc_num', models.IntegerField(unique=True)),
                ('card_code', models.CharField(max_length=50)),
                ('card_name', models.CharField(max_length=200)),
                ('doc_date', models.DateField()),
                ('doc_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('slp_code', models.CharField(max_length=20)),
                ('slp_name', models.CharField(max_length=100)),
                ('secuencia_ruta', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Listo en almacén'), ('Asignado', 'En preparación'), ('En_Camino', 'En ruta'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.destino')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones', to='delivery.ruta')),
            ],
        ),
    ]
