# Generated by Django 6.0.6 on 2026-07-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='eta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
