# Generated by Django 6.0.6 on 2026-07-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remision_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'En preparación'), ('Cargando', 'Cargando mercancía'), ('Listo', 'Listo para salir'), ('En_Ruta', 'En ruta'), ('Finalizada', 'Finalizada')], default='Borrador', max_length=20),
        ),
    ]
