# Generated by Django 6.0.6 on 2026-07-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_ruta_hora_salida_alter_ruta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='peso_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
