# Generated by Django 6.0.6 on 2026-07-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remision_peso_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='contacto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='destino',
            name='referencias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destino',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
