# Generated by Django 6.0.6 on 2026-07-26 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_destino_contacto_destino_referencias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='entregado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remision',
            name='motivo',
            field=models.CharField(blank=True, choices=[('cliente_rechazo', 'El cliente aceptó menos de lo que traía'), ('producto_danado', 'Producto dañado o en mal estado'), ('falto_en_camion', 'No venía completo en el camión'), ('cerrado', 'El cliente estaba cerrado'), ('sin_quien_reciba', 'No había quién recibiera'), ('sin_espacio', 'El cliente no tenía dónde meterlo'), ('otro', 'Otro motivo')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='remision',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remision',
            name='recibio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='remision',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Listo en almacén'), ('Asignado', 'En preparación'), ('En_Camino', 'En ruta'), ('Entregado', 'Entregado completo'), ('Entregado_Parcial', 'Entregado incompleto'), ('No_Entregado', 'No se pudo entregar')], default='Pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='LineaRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_num', models.IntegerField()),
                ('item_code', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('unidad', models.CharField(blank=True, max_length=30, null=True)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('peso_unitario_kg', models.FloatField(blank=True, null=True)),
                ('cantidad_entregada', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='delivery.remision')),
            ],
            options={
                'ordering': ['line_num'],
                'unique_together': {('remision', 'line_num')},
            },
        ),
    ]
