# Generated by Django 6.0.6 on 2026-07-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_remision_entregado_en_remision_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='entregas/%Y/%m/'),
        ),
    ]
