# Generated by Django 5.2.16 on 2026-07-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0007_remision_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="remision",
            name="firma",
            field=models.ImageField(blank=True, null=True, upload_to="firmas/%Y/%m/"),
        ),
    ]
