# Generated by Django 5.2.16 on 2026-08-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_remision_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='regreso_plan',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='salida_plan',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
