# Generated by Django 5.2.16 on 2026-08-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_ruta_unica_por_fecha_y_camion'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearemision',
            name='piezas_por_unidad',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
